setwd("G:\\Projects\\R\\Exploratory\\project1\\ExData_Plotting1")

dataFile <- read.table("h1.txt", sep=";", header=T,as.is=TRUE)
dataFile$Date <- as.Date(dataFile$Date,format="%d/%m/%Y")
d1 <- paste(dataFile$Date,dataFile$Time)
dataFile$DateTime <- as.POSIXct(d1)
#dataFile$DateTime <- d1


par(mfrow=c(1,1),new=F)
#with(dataFile,plot(DateTime,Sub_metering_1))
with(dataFile,plot(DateTime, Sub_metering_1,type="l", xaxt="n",ylab="Energy Submetering",xlab=""))
#line(weekdays(dataFile$DateTime),as.numeric(as.character(dataFile$Sub_metering_1)))
#with(dataFile, plot(as.numeric(Sub_metering_1),type="l",xlab="", xaxt="n",ylab="Energy Submetering",axes=FALSE,frame.plot=TRUE))
#with(dataFile,plot(DateTime, Sub_metering_1,type="n", xaxt="n"))
#with(dataFile, points(DateTime,type="l",col="black"))
#with(dataFile, plot(Sub_metering_2,type="l",xaxt="n",xlab="", ylab="Global Active Power (kilowatts)",col="red"))
#with(dataFile, plot(Sub_metering_3,type="l",xaxt="n",xlab="", ylab="Global Active Power (kilowatts)",col="blue"))
#with(dataFile, points(DateTime,Sub_metering_1,col="black",type="l"))
with(dataFile, points(DateTime,Sub_metering_2,col="red",type="l"))
with(dataFile, points(DateTime,Sub_metering_3,col="blue",type="l"))
#axis(2)
mini <- min(dataFile$DateTime)
#print(as.numeric(mini))
axis(side=1, at=c(mini, mini+86400, mini+2*86400),labels=c("Thu","Fri","Sat"))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),col=c("black","red","blue"),seg.len=.5)
#hist(dataFile$Sub_metering_1)
#print(par("usr"))